sudo: required
services:
  - docker

before_install:
  - docker build -t louisctg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true louisctg/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-2-066496208359"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"